### ISSUE TITLE
Auto-accept first submission prevents subsequent submission

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#591]
On http://australia.census.okfn.org/place/nsw/2015 it shows two entries for NSW Contracts
The first:
Status: Awaiting Review  (but Accepted according to http://australia.census.okfn.org/changes/)
Submission date: 12:31pm on 4th Mar 2015
Submitter:Anonymous
Reviewer: Australia's Open Data Index

The second (according to http://australia.census.okfn.org/entry/nsw/contracts/2015 ) is 
Status: Accepted (according to http://australia.census.okfn.org/changes/)
Date:  Sun Mar 22 2015 11:56:39 
Submitter: Anonymous
Reviewer: Stephen Gates 

I can't propose changes to the second entry or approve [the first](http://australia.census.okfn.org/census/submission/93f2939b-4078-42a0-928b-d4bd33c2432b)

<img width="1070" alt="screenshot 2015-07-23 21 01 35" src="https://cloud.githubusercontent.com/assets/9379524/8848847/220401a6-317e-11e5-868b-ee9911370b64.png">

Now this may be self inflicted. I did change the config file (but couldn't reload it due to #578) and added `approve_first_submission = TRUE`

Why?  Because I don't like this messy look of auto-accepted submissions waiting for review... 
<img width="779" alt="screenshot 2015-07-23 21 12 30" src="https://cloud.githubusercontent.com/assets/9379524/8849045/bab04e86-317f-11e5-8ccc-44f2f9ff6309.png">

**Comment by Stephen-Gates** [comment]
May be related or separate issue. On http://australia.census.okfn.org/place/qld/2015 I have a couple of dataset with multiple submissions awaiting review. These two entries were added by the same person half an hour apart. 
<img width="964" alt="screenshot 2015-07-23 21 39 16" src="https://cloud.githubusercontent.com/assets/9379524/8849510/a442d5f2-3183-11e5-8a96-fe1686584c39.png">

**Comment by pwalsh** [comment]
@Stephen-Gates :

1. NSW / Procurement Contracts - there is only one submission waiting, not two. You can't propose a revision because one is waiting (ie: a revision has already been proposed).

2. Is there any way to ask earl what course of action he took to add submissions? it should not be possible to add two submissions. I'm checking now.

**Comment by Stephen-Gates** [comment]
@pwalsh 
 1. Ok but can't approve NSW / Contracts as there's no button on the [submission review form] (http://australia.census.okfn.org/census/submission/93f2939b-4078-42a0-928b-d4bd33c2432b)  

 2. I think I know Earl B. given the dataset and place. I'll ask over the next few days. I plan to reject both entries so it would be good to explain that as well.

 3. Brain turning to mush - too much testing  ;-)

**Comment by Stephen-Gates** [comment]
@pwalsh Earl reports "I added the DCCSDS service / contact centres. I did experience a surprise feature when I was adding my listing. I was still adding details when the listing was posted without any confirmation if I had finished".

**Comment by pwalsh** [comment]
Well, the only way to "post" is to click the button. Possibly an accidental click?

**Comment by pwalsh** [comment]
Hi @Stephen-Gates I now addressed a bunch of behaviour related to the queuing of submissions, and the display of them. There were some old submissions showing that should not have been (they were in the past, earlier than the entries that are displayed).

I do believe this till address all the issues you listed here. Could you please verify, and if you still have any issues related, please open a distinct issue here for each problem - it makes it easier to keep track of things.

Meanwhile, I'm closing this ticket.

**Comment by Stephen-Gates** [comment]
@pwalsh Looks right to me. 
Earl's double entry problem remains - will raise as separate issue.
