### ISSUE TITLE
[Local census] Dataset translation is not loading

### ISSUE THREAD

**Issue by schlos** [okfn/opendatacensus#868]
**Precondition:**

Added locales (hr en de) to [Open Data Census - Config HR City / Config sheet](https://docs.google.com/spreadsheets/d/1FCAnp_sksyb2FREVjw-qpDbJEVo5efRqiQP1OT1krDM/edit#gid=0).

Added datasets translations in [Open Data Census - Config HR City / Datasets sheet](https://docs.google.com/spreadsheets/d/1FCAnp_sksyb2FREVjw-qpDbJEVo5efRqiQP1OT1krDM/edit#gid=2), columns named Title@HR, Description@HR, Title@DE, Description@DE.

On [Admin page](http://hr-city.census.okfn.org/admin), I've reloaded Config and Dashboard -> Resulted with OK.

**Problem:**

When [on site](http://hr-city.census.okfn.org/) switch language between hr and en (in footer), the site language changes but dataset names and description stays always locked in English language.

Screenshot:

![pregled - city open data census croatia](https://cloud.githubusercontent.com/assets/1014134/21486148/4671a418-cbaf-11e6-84e0-c5b86573333a.jpg)

**Expected:**

When switching locale language, it should switch both transifex translation to selected language and datasets translations.

**Comment by brew** [comment]
It looks like you're refering to the old version of the index (at *.index.okfn.org). There are know problems with localization in that version. These have since been resolved in the new version (hosted at *.survey.okfn.org) in #844.

**Comment by schlos** [comment]
There is no "http://hr-city.survey.okfn.org" *.survey.okfn.org like you suggested. So there is still existing problem with *.index.okfn.org site. Any plans to fix these issue or migrate index sites to survey?

**Comment by tlacoyodefrijol** [comment]
Hi @schlos we can create an instance for you. Can you send me an email to oscar.montiel@okfn.org so we can go through the details?
